CREATE TABLE IF NOT EXISTS PUBLIC.SCORE (
  USER_ID BIGINT,
  CHAT_ID VARCHAR(100),
  SCORE BIGINT,
  CONSTRAINT PK_SCORE PRIMARY KEY (USER_ID, CHAT_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USER (
  USER_ID BIGINT,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  USERNAME VARCHAR(100),
  CONSTRAINT PK_USER PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.QUESTION_DATA (
	RESULT_TS VARCHAR(100),
	RESULT_ID VARCHAR(100),
	QUESTION_DATA TEXT,
	QUESTION_ANSWER TEXT,
	CONSTRAINT PK_QUESTION_DATA PRIMARY KEY ( RESULT_TS, RESULT_ID )
);
